//// COURSES
export const CREATE_COURSE = 'CREATE_COURSE';
export const FETCH_COURSE = 'FETCH_COURSE';
export const LOAD_COURSES = 'LOAD_COURSES';
export const SAVE_COURSE = 'SAVE_COURSE';
export const SAVE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';
export const SAVE_COURSE_FAILURE = 'SAVE_COURSE_FAILURE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_COURSES_FAILURE = 'LOAD_COURSES_FAILURE';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const CREATE_COURSE_FAILURE = 'CREATE_COURSE_FAILURE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAILURE = 'DELETE_COURSE_FAILURE';

//// AUTHORS
export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const FETCH_AUTHOR = 'FETCH_AUTHOR';
export const LOAD_AUTHORS = 'LOAD_AUTHORS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const LOAD_AUTHORS_FAILURE = 'LOAD_AUTHORS_FAILURE';
export const SAVE_AUTHOR = 'SAVE_AUTHOR';
export const SAVE_AUTHOR_SUCCESS = 'SAVE_AUTHOR_SUCCESS';
export const SAVE_AUTHOR_FAILURE = 'SAVE_AUTHOR_FAILURE';
export const CREATE_AUTHOR_SUCCESS = 'CREATE_AUTHOR_SUCCESS';
export const CREATE_AUTHOR_FAILURE = 'CREATE_AUTHOR_FAILURE';
export const UPDATE_AUTHOR_SUCCESS = 'UPDATE_AUTHOR_SUCCESS';
export const UPDATE_AUTHOR_FAILURE = 'UPDATE_AUTHOR_FAILURE';

//// AJAX
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const AJAX_CALL_SUCCESS = 'AJAX_CALL_SUCCESS';

//// MISC
export const UPDATE_ERRORS = 'UPDATE_ERRORS';
export const RESET_ERRORS = 'RESET_ERRORS';
